apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicant
spec:
  selector:
    matchLabels:
      app: applicant
  template:
    metadata:
      labels:
        app: applicant
    spec:
      containers:
      - name: applicant
        image: 296062552975.dkr.ecr.ap-northeast-2.amazonaws.com/ec2-team-backend:411f623906fc070a16357a4ad07f20b21ae8aa3a 296062552975.dkr.ecr.ap-northeast-2.amazonaws.com/ec2-team-backend:cbe564cace582ff242c94d124607f17ae4b8aad4
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
