apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: 296062552975.dkr.ecr.ap-northeast-2.amazonaws.com/ec2-team-frontend:fca2cf1e98ec5dcd91e41eb33d7d1d584fefc047
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
