apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: 296062552975.dkr.ecr.ap-northeast-2.amazonaws.com/ec2-team-frontend:7ad13c542f6a5f432047ccba6d8c1bd6d5d6b4d5 296062552975.dkr.ecr.ap-northeast-2.amazonaws.com/ec2-team-frontend:69184d4c7b7e50eb3f31d6c3947601f11a635b72
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
